article_index:
    path:     /
    defaults: { _controller: "PortalBundle:Articles:index" }
    methods:  GET

article_show:
    path:     /{id}/show
    defaults: { _controller: "PortalBundle:Articles:show" }
    methods:  GET

article_new:
    path:     /new
    defaults: { _controller: "PortalBundle:Articles:new" }
    methods:  [GET, POST]

article_edit:
    path:     /{id}/edit
    defaults: { _controller: "PortalBundle:Articles:edit" }
    methods:  [GET, POST]

article_delete:
    path:     /{id}/delete
    defaults: { _controller: "PortalBundle:Articles:delete" }
    methods:  DELETE
