comment_index:
    path:     /
    defaults: { _controller: "PortalBundle:Comments:index" }
    methods:  GET

comment_show:
    path:     /{id}/show
    defaults: { _controller: "PortalBundle:Comments:show" }
    methods:  GET

comment_new:
    path:     /new
    defaults: { _controller: "PortalBundle:Comments:new" }
    methods:  [GET, POST]

comment_edit:
    path:     /{id}/edit
    defaults: { _controller: "PortalBundle:Comments:edit" }
    methods:  [GET, POST]

comment_delete:
    path:     /{id}/delete
    defaults: { _controller: "PortalBundle:Comments:delete" }
    methods:  DELETE
