image_index:
    path:     /
    defaults: { _controller: "PortalBundle:Images:index" }
    methods:  GET

image_show:
    path:     /{id}/show
    defaults: { _controller: "PortalBundle:Images:show" }
    methods:  GET

image_new:
    path:     /new
    defaults: { _controller: "PortalBundle:Images:new" }
    methods:  [GET, POST]

image_edit:
    path:     /{id}/edit
    defaults: { _controller: "PortalBundle:Images:edit" }
    methods:  [GET, POST]

image_delete:
    path:     /{id}/delete
    defaults: { _controller: "PortalBundle:Images:delete" }
    methods:  DELETE
