user_index:
    path:     /
    defaults: { _controller: "PortalBundle:Users:index" }
    methods:  GET

user_show:
    path:     /{id}/show
    defaults: { _controller: "PortalBundle:Users:show" }
    methods:  GET

user_new:
    path:     /new
    defaults: { _controller: "PortalBundle:Users:new" }
    methods:  [GET, POST]

user_edit:
    path:     /{id}/edit
    defaults: { _controller: "PortalBundle:Users:edit" }
    methods:  [GET, POST]

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "PortalBundle:Users:delete" }
    methods:  DELETE
