PortalBundle\Entity\Comments:
    type: entity
    table: comments
    indexes:
        fk_article_comment:
            columns:
                - comment_article_id
    id:
        commentId:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: comment_id
            generator:
                strategy: IDENTITY
    fields:
        commentText:
            type: text
            nullable: false
            length: 65535
            fixed: false
            column: comment_text
    manyToOne:
        commentArticle:
            targetEntity: Articles
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                comment_article_id:
                    referencedColumnName: article_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
