PortalBundle\Entity\Images:
    type: entity
    table: images
    indexes:
        fk_article_images:
            columns:
                - image_article_id
    id:
        imageId:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: image_id
            generator:
                strategy: IDENTITY
    fields:
        imageLink:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: image_link
    manyToOne:
        imageArticle:
            targetEntity: Articles
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                image_article_id:
                    referencedColumnName: article_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
